### ISSUE TITLE
Add option to manually specify BurpSuite install folder

### ISSUE THREAD

**Issue by ZhymabekRoman** [mmgordon82/BurpSuiteInstaller#2]
I have some old HHD, and searching through all the folders on the root create huge drive noises. Also thanks for the work!

**Comment by mmgordon82** [comment]
Good Idea! 
Will do! Stay tuned.

Thanks.

**Comment by mmgordon82** [comment]
Hi there,
Because of this issue I took another look at the find command used to search for the Burp installation and it does seem excessive. I added `max-depth` with a decent value and limited it from entering some directories. The automatic lookup should be faster now.

Moreover, now the script can take an argument for a specific burp installation. From the source:
```
# Burp Suite Pro Patch Script
# Usage:
#   ./burp-suite-patch.sh [path to burp *.vmoptions file or install directory]
# Example:
#   ./burp-suite-patch.sh                                           # Finds the vmoptions file automatically
#   ./burp-suite-patch.sh /opt/BurpSuitePro/BurpSuitePro.vmoptions  # Manually specified path to the vmoptions file
#   ./burp-suite-patch.sh /opt/BurpSuitePro/                        # Same as above, but with install directory
```

Feel free to specify your burp installation. The updated code is in the latest Github release (or in `linux/` in this repo if you prefer switching the existing script)

**Comment by ZhymabekRoman** [comment]
Thanks!
