### ISSUE TITLE
Can not run in Macos

### ISSUE THREAD

**Issue by akshin-autods** [mmgordon82/BurpSuiteInstaller#8]
I am trying to run this code 
`bash burp-suite-patch.sh ~/Downloads/Burp\ Suite\ Pro\ v2024.2.1.5.jar `
And i get next thing 
`[+] Patching Burp Suite installation at /Users/akshin/Downloads...
[+] Patching /Users/akshin/Downloads/Burp Suite Pro v2024.2.1.5.jar...
[+] Creating 'activation.vmoptions' file...
[+] Copying BurpLoaderKeygen.jar file...
[+] Finished!

Activation Instructions:
1. Run the keygen
2. Copy the activation code to burp and proceed
3. Click Manual Activation
4. Copy Activation request to the keygen
5. Copy the generated activation response to burp and activate
6. That's it ;)

Press [Enter] key to start BurpSuite and the Keygen to start the activation process...
[+] Starting Burp Suite...
[+] Starting the keygen...
burp-suite-patch.sh: line 132: /Users/me/Downloads/BurpSuitePro: No such file or directory
burp-suite-patch.sh: line 134: /Users/me/Downloads/jre/bin/java: No such file or directory`

**Comment by mmgordon82** [comment]
Thanks for letting me know. I havent really tested on Macos, but I'll borrow a friend's and see what's up with this in the next few days.

**Comment by akshin-autods** [comment]
i have already resolved this issue. i have just followed tge guid the git hub repository that appears when i searchng in github ceacked version it is in chines language i guess

**Comment by mmgordon82** [comment]
Hi,
Thanks for the update on the macOS issue.
I've updated the README.md to include a section on [installing Burp on macOS](https://github.com/mmgordon82/BurpSuiteInstaller?tab=readme-ov-file#macos).

Please be aware that the crack applies to the full Burp Suite product installation provided on PortSwigger's site (i.e., a dmg file with JRE included builtin) rather than a standalone JAR file download.

Tested on MacBook Air M1. Closing the issue.
